MESSAGE = """You are an AI language model tasked with analyzing a given text document and classifying it according to a specified set of subregisters from the Turku-developed CORE scheme. For each subregister, assign a **1** if the document matches the subregister, and a **0** if it does not.

**Instructions:**

1. **Carefully read the entire document provided.**

2. **For each subregister listed below:**

   - Refer to the **definition** provided for each subregister.
   - Determine whether the document exhibits the characteristics of that subregister.
   - Assign a **1** if it matches the subregister, or a **0** if it does not.

3. **Ensure that every subregister is assigned either a 1 or a 0.**

4. **Structure your output** exactly as specified in the "Output Format" section.

5. **Do not include any additional commentary, explanations, or analysis** beyond the classifications.

---

### **Subregisters and Definitions**

**MACHINE TRANSLATED OR GENERATED (MT):**

- **Definition:** Texts that have been translated by a machine or generated by an AI, possibly exhibiting unnatural phrasing or errors.

**LYRICAL (LY):**

- **Definition:** Texts that are poetic or song-like in nature, focusing on artistic expression.

**SPOKEN (SP):**

- **Interview (it):**

  - **Definition:** Transcriptions of interviews, typically in a question-and-answer format.

- **Other spoken (os):**

  - **Definition:** Other spoken language texts, such as speeches, dialogues, or transcribed conversations.

**INTERACTIVE DISCUSSION (ID):**

- **Definition:** Texts involving interactive communication, such as forum posts, comments, or online discussions.

**NARRATIVE (NA):**

- **News report (ne):**

  - **Definition:** Articles reporting on recent events in a factual manner.

- **Sports report (sr):**

  - **Definition:** Reports covering sports events, matches, or related news.

- **Narrative blog (nb):**

  - **Definition:** Blog posts that narrate personal experiences or stories.

- **Other narrative (on):**

  - **Definition:** Other narrative texts not covered above, including fiction and storytelling.

**HOW-TO or INSTRUCTIONS (HI):**

- **Recipe (re):**

  - **Definition:** Instructions for preparing food and beverages.

- **Other how-to (oh):**

  - **Definition:** Guides or tutorials on how to perform tasks or activities.

**INFORMATIONAL DESCRIPTION (IN):**

- **Encyclopedia article (en):**

  - **Definition:** Comprehensive articles providing factual information on specific topics.

- **Research article (ra):**

  - **Definition:** Scholarly articles presenting original research findings.

- **Description of a thing or person (dtp):**

  - **Definition:** Detailed descriptions of objects, places, or individuals.

- **FAQ (fi):**

  - **Definition:** Lists of frequently asked questions with corresponding answers.

- **Legal terms and conditions (lt):**

  - **Definition:** Formal legal documents outlining terms, conditions, or policies.

- **Other informational description (oi):**

  - **Definition:** Informational texts not covered above, providing factual descriptions.

**OPINION (OP):**

- **Review (rv):**

  - **Definition:** Evaluations or critiques of products, services, or creative works.

- **Opinion blog (ob):**

  - **Definition:** Blog posts expressing personal opinions or commentary.

- **Denominational religious blog / sermon (rs):**

  - **Definition:** Religious texts offering teachings, sermons, or reflections.

- **Advice (av):**

  - **Definition:** Texts providing guidance or recommendations based on personal opinions.

- **Other opinion (oo):**

  - **Definition:** Opinionated texts not covered above.

**INFORMATIONAL PERSUASION (IP):**

- **Description with intent to sell (ds):**

  - **Definition:** Texts describing products or services with the aim of persuading purchase.

- **News & opinion blog or editorial (ed):**

  - **Definition:** Articles combining news reporting with opinion or editorial commentary.

- **Other informational persuasion (oe):**

  - **Definition:** Persuasive texts providing information to influence the reader.

---

### **Output Format**

Provide your classifications in the exact format below, replacing `[0 or 1]` with either **1** or **0** for each subregister:

```
MT (Machine Translated or Generated): [0 or 1]
LY (Lyrical): [0 or 1]
SP (Spoken):
  - it (Interview): [0 or 1]
  - os (Other spoken): [0 or 1]
ID (Interactive Discussion): [0 or 1]
NA (Narrative):
  - ne (News report): [0 or 1]
  - sr (Sports report): [0 or 1]
  - nb (Narrative blog): [0 or 1]
  - on (Other narrative): [0 or 1]
HI (How-to or Instructions):
  - re (Recipe): [0 or 1]
  - oh (Other how-to): [0 or 1]
IN (Informational Description):
  - en (Encyclopedia article): [0 or 1]
  - ra (Research article): [0 or 1]
  - dtp (Description of a thing or person): [0 or 1]
  - fi (FAQ): [0 or 1]
  - lt (Legal terms and conditions): [0 or 1]
  - oi (Other informational description): [0 or 1]
OP (Opinion):
  - rv (Review): [0 or 1]
  - ob (Opinion blog): [0 or 1]
  - rs (Religious blog / sermon): [0 or 1]
  - av (Advice): [0 or 1]
  - oo (Other opinion): [0 or 1]
IP (Informational Persuasion):
  - ds (Description with intent to sell): [0 or 1]
  - ed (News & opinion blog or editorial): [0 or 1]
  - oe (Other informational persuasion): [0 or 1]
```

**Example Output:**

```
MT (Machine Translated or Generated): 0
LY (Lyrical): 0
SP (Spoken):
  - it (Interview): 0
  - os (Other spoken): 0
ID (Interactive Discussion): 1
NA (Narrative):
  - ne (News report): 0
  - sr (Sports report): 0
  - nb (Narrative blog): 1
  - on (Other narrative): 0
HI (How-to or Instructions):
  - re (Recipe): 0
  - oh (Other how-to): 0
IN (Informational Description):
  - en (Encyclopedia article): 0
  - ra (Research article): 0
  - dtp (Description of a thing or person): 0
  - fi (FAQ): 0
  - lt (Legal terms and conditions): 0
  - oi (Other informational description): 0
OP (Opinion):
  - rv (Review): 0
  - ob (Opinion blog): 1
  - rs (Religious blog / sermon): 0
  - av (Advice): 0
  - oo (Other opinion): 0
IP (Informational Persuasion):
  - ds (Description with intent to sell): 0
  - ed (News & opinion blog or editorial): 0
  - oe (Other informational persuasion): 0
```

---

### **Document to Analyze**

{}

---

**Remember:**

- **Accuracy is crucial.** Base your classifications on the content and characteristics of the document.
- **Consistency is key.** Use the same criteria for each subregister across different documents.
- **No explanations are needed.** Only provide the classifications as per the output format.

**Begin your analysis after the document is provided.**
"""
