MESSAGE = """You are an AI language model tasked with analyzing a given text document and rating it according to a specified set of subregisters from the Turku-developed CORE scheme. For each subregister, assign a score from **1 to 6** based on how well the document exhibits the characteristics of that subregister:

- **1 (Completely Disagree):** The document does not exhibit characteristics of this subregister at all.
- **2 (Mostly Disagree):** The document exhibits minimal characteristics of this subregister.
- **3 (Slightly Disagree):** The document somewhat lacks characteristics of this subregister.
- **4 (Slightly Agree):** The document somewhat exhibits characteristics of this subregister.
- **5 (Mostly Agree):** The document largely exhibits characteristics of this subregister.
- **6 (Completely Agree):** The document fully exhibits characteristics of this subregister.

**Instructions:**

1. **Carefully read the entire document provided.**

2. **For each subregister listed below:**

   - Refer to the **definition** provided for each subregister.
   - Assess the document's content, style, and purpose against these characteristics.
   - Assign a score from **1 to 6** based on the alignment.

3. **Ensure that every subregister is rated**, even if the score is **1 (Completely Disagree)**.

4. **Structure your output** exactly as specified in the "Output Format" section.

5. **Do not include any additional commentary, explanations, or analysis** beyond the scores.

---

### **Subregisters and Definitions**

**MACHINE TRANSLATED OR GENERATED (MT):**

- **Definition:** Texts that have been translated by a machine or generated by an AI, possibly exhibiting unnatural phrasing or errors.

**LYRICAL (LY):**

- **Definition:** Texts that are poetic or song-like in nature, focusing on artistic expression.

**SPOKEN (SP):**

- **Interview (it):**

  - **Definition:** Transcriptions of interviews, typically in a question-and-answer format.

- **Other spoken (os):**

  - **Definition:** Other spoken language texts, such as speeches, dialogues, or transcribed conversations.

**INTERACTIVE DISCUSSION (ID):**

- **Definition:** Texts involving interactive communication, such as forum posts, comments, or online discussions.

**NARRATIVE (NA):**

- **News report (ne):**

  - **Definition:** Articles reporting on recent events in a factual manner.

- **Sports report (sr):**

  - **Definition:** Reports covering sports events, matches, or related news.

- **Narrative blog (nb):**

  - **Definition:** Blog posts that narrate personal experiences or stories.

- **Other narrative (on):**

  - **Definition:** Other narrative texts not covered above, including fiction and storytelling.

**HOW-TO or INSTRUCTIONS (HI):**

- **Recipe (re):**

  - **Definition:** Instructions for preparing food and beverages.

- **Other how-to (oh):**

  - **Definition:** Guides or tutorials on how to perform tasks or activities.

**INFORMATIONAL DESCRIPTION (IN):**

- **Encyclopedia article (en):**

  - **Definition:** Comprehensive articles providing factual information on specific topics.

- **Research article (ra):**

  - **Definition:** Scholarly articles presenting original research findings.

- **Description of a thing or person (dtp):**

  - **Definition:** Detailed descriptions of objects, places, or individuals.

- **FAQ (fi):**

  - **Definition:** Lists of frequently asked questions with corresponding answers.

- **Legal terms and conditions (lt):**

  - **Definition:** Formal legal documents outlining terms, conditions, or policies.

- **Other informational description (oi):**

  - **Definition:** Informational texts not covered above, providing factual descriptions.

**OPINION (OP):**

- **Review (rv):**

  - **Definition:** Evaluations or critiques of products, services, or creative works.

- **Opinion blog (ob):**

  - **Definition:** Blog posts expressing personal opinions or commentary.

- **Denominational religious blog / sermon (rs):**

  - **Definition:** Religious texts offering teachings, sermons, or reflections.

- **Advice (av):**

  - **Definition:** Texts providing guidance or recommendations based on personal opinions.

- **Other opinion (oo):**

  - **Definition:** Opinionated texts not covered above.

**INFORMATIONAL PERSUASION (IP):**

- **Description with intent to sell (ds):**

  - **Definition:** Texts describing products or services with the aim of persuading purchase.

- **News & opinion blog or editorial (ed):**

  - **Definition:** Articles combining news reporting with opinion or editorial commentary.

- **Other informational persuasion (oe):**

  - **Definition:** Persuasive texts providing information to influence the reader.

---

### **Output Format**

Provide your ratings in the exact format below, replacing `[Score]` with the number from **1 to 6** for each subregister:

```
MT (Machine Translated or Generated): [Score]
LY (Lyrical): [Score]
SP (Spoken):
  - it (Interview): [Score]
  - os (Other spoken): [Score]
ID (Interactive Discussion): [Score]
NA (Narrative):
  - ne (News report): [Score]
  - sr (Sports report): [Score]
  - nb (Narrative blog): [Score]
  - on (Other narrative): [Score]
HI (How-to or Instructions):
  - re (Recipe): [Score]
  - oh (Other how-to): [Score]
IN (Informational Description):
  - en (Encyclopedia article): [Score]
  - ra (Research article): [Score]
  - dtp (Description of a thing or person): [Score]
  - fi (FAQ): [Score]
  - lt (Legal terms and conditions): [Score]
  - oi (Other informational description): [Score]
OP (Opinion):
  - rv (Review): [Score]
  - ob (Opinion blog): [Score]
  - rs (Religious blog / sermon): [Score]
  - av (Advice): [Score]
  - oo (Other opinion): [Score]
IP (Informational Persuasion):
  - ds (Description with intent to sell): [Score]
  - ed (News & opinion blog or editorial): [Score]
  - oe (Other informational persuasion): [Score]
```

**Example Output:**

```
MT (Machine Translated or Generated): 1
LY (Lyrical): 2
SP (Spoken):
  - it (Interview): 1
  - os (Other spoken): 1
ID (Interactive Discussion): 4
NA (Narrative):
  - ne (News report): 2
  - sr (Sports report): 1
  - nb (Narrative blog): 5
  - on (Other narrative): 3
HI (How-to or Instructions):
  - re (Recipe): 1
  - oh (Other how-to): 2
IN (Informational Description):
  - en (Encyclopedia article): 1
  - ra (Research article): 1
  - dtp (Description of a thing or person): 4
  - fi (FAQ): 2
  - lt (Legal terms and conditions): 1
  - oi (Other informational description): 3
OP (Opinion):
  - rv (Review): 2
  - ob (Opinion blog): 5
  - rs (Religious blog / sermon): 1
  - av (Advice): 4
  - oo (Other opinion): 3
IP (Informational Persuasion):
  - ds (Description with intent to sell): 2
  - ed (News & opinion blog or editorial): 4
  - oe (Other informational persuasion): 3
```

---

### **Document to Analyze**

{}

---

**Remember:**

- **Accuracy is crucial.** Base your scores on the content and characteristics of the document.
- **Consistency is key.** Use the same criteria for each subregister across different documents.
- **No explanations are needed.** Only provide the scores as per the output format.

**Begin your analysis after the document is provided.**

"""
